In [91]:
K = [[1, 2, 3], [1, 3, 4], [1, 2, 4], [2, 3, 4]]

In [79]:
from itertools import combinations

def find_p_simplices(K, p):
    p_simplicies = set()

    for simplex in K:
        faces = sorted(simplex)

        if len(faces) == p+1:
            p_simplicies.add(tuple(faces))
        elif len(faces) > p+1:
            for face in combinations(faces, p+1):
                p_simplicies.add(face)
    
    return [list(simplex) for simplex in p_simplicies]


In [80]:
print(find_p_simplices(K, 1))

[[2, 4], [1, 2], [3, 4], [2, 3], [1, 3]]


In [81]:
import galois
import numpy as np

In [82]:
def find_p_boundary(K, p):
    p_simplices = find_p_simplices(K, p)
    prev_simplices = find_p_simplices(K, p-1)
    
    face_to_index = {tuple(sorted(f)): i for i, f in enumerate(prev_simplices)}
    
    GF2 = galois.GF(2)
    matrix = GF2.Zeros((len(prev_simplices), len(p_simplices)))
    
    for j, simplex in enumerate(p_simplices):
        for i in range(len(simplex)):
            face = tuple(sorted(list(simplex)[:i] + list(simplex)[i+1:]))
            if face in face_to_index:
                row_idx = face_to_index[face]
                matrix[row_idx, j] = 1
                
    return matrix

In [97]:
b2 = find_p_boundary(K, 2)
print(b2)
b3 = find_p_boundary(K, 3)
print(b3)

[[1 0 1 0]
 [0 1 1 0]
 [1 0 0 1]
 [0 0 1 1]
 [1 1 0 0]
 [0 1 0 1]]
[]


In [98]:
rank_Z2 = b2.null_space().shape[0]
print(rank_Z2)
rank_B3 = np.linalg.matrix_rank(b3)
print(rank_B3)

1
0


In [99]:
rankH1 = rank_Z2 - rank_B3
print(rankH1)

1
